spring:
  h2:
    console:
      enabled: true
      path: /h2-console

#  MYSQL SETTINGS

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: com.jhsfully.reservation.dialect.MySQLCustomDialect

  datasource:
    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


#  H2 DATABASE SETTINGS

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:jhsfully
#    username: sa
#    password:

  redis:
    host: localhost
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    secret: ENTER_YOUR_JWT_SECRET_KEY!!!