spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#    database: mysql

#  datasource:
#    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 12341234

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jhsfully
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: ENTER_YOUR_JWT_SECRET_KEY!!!